<?php

namespace App\Enums;

class ElementReplace
{
    const LIST_ITCHIO = [
        '<meta name="theme-color"',
        '<meta content="itch.io" property="og:site_name">',
        'property="twitter:account_id"',
        'property="og:description"',
        'meta name="description"',
        '<meta content="width=device-width, initial-scale=1" name="viewport">',
        '<meta content="@itchio" name="twitter:site">',
        '<meta content="summary_large_image" name="twitter:card">',
        '<meta property="og:image"',
        '<meta name="twitter:title"',
        '<meta name="twitter:description"',
        '<meta name="itch:path"',
        'property="twitter:image">',
        '<meta name="twitter:url"',
        '<script type="application/ld+json">',
        '<meta name="csrf_token"',
        '<script type="text/javascript">window.itchio_translations_url',
        '(i[r].q=i[r].q||[])',
        'm=s.getElementsByTagName(o)[0]',
        '})(window,document,',
        'ga("create", {',
        'ga("set",',
        'ga("send",',
        'ga("require",',
        '<script type="text/template" id="vote_counts_tpl"><% if (up_score > 0) { %><span class="upvotes">(+{{up_score}})<% } %><% if (down_score > 0) { %><span class="downvotes">(-{{down_score}})<% } %></script>',
        '<meta property="twitter:creator"',
        '<meta property="twitter:image"',
        '<link type="application/rss+xml"',
        '<link type="image/gif" rel="icon"',
        'property="twitter:creator">',
        'type="image/gif">',
        '<div class="donate">',
        'href="https://itch.io/games/released"',
        'href="https://itch.io/games/platform-windows"',
        'https://itch.io/login?return_to=https',
        '<h2 id="comments">',
        '<p class="form_placeholder">',
        '<span class="page_label">',
        'property="og:image"',
        'follow_user_btn action_btn',
        'https://itch.io/login?',
        'https://itch.io/profile/',
        'embed_preload youtube_preload',
        '<link type="image/png" rel="icon"',
        'action_btn view_more',
        'community_link',
        'devlog_link',
        '<p>',
        'abbr title',
        '<td>Updated</td>',
        '<td>Published</td>',
        '<td>Status</td>',
        '<td>Rating</td>',
        '<td>Platforms</td>',
        '"screenreader_only"',
        'id="download"',
        'download_platforms',
        'class="game_devlog"',
        'href="https://itch.io/games">Games',
        '>I.setup_layout()',
        '.itch.io',
    ];
}
